version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      open-telemetry:
        patterns:
          - "@opentelemetry/*"
      testing:
        dependency-type: development
        patterns:
          - "vitest"
          - "@testing-library/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
